<a href="https://colab.research.google.com/github/maddygoodro/MIS433/blob/main/assignment_IMDB_manipulation_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [1]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Data/imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [4]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [5]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [6]:
# Display top 10 movies' title, released year and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].head(10)

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [13]:
# Display movies ranked 11-20.
# Show their title, released year and IMDB rating.
(
    imdb.sort_values(by="IMDB_Rating", ascending=False) #must sort by rating to retrieve ranked 11-20, then sort descending to show top rows
    [['Series_Title', 'Released_Year', 'IMDB_Rating']] #now get all column names we want DOUBLE BRACKETS and QUOTES
   .iloc[10:20] ) #iloc is to split on ROWS, returns the 11th through 20th row based on the filters listed first

,Series_Title,Released_Year,IMDB_Rating
11,Forrest Gump,1994,8.8
10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
9,Fight Club,1999,8.8
14,The Matrix,1999,8.7
13,The Lord of the Rings: The Two Towers,2002,8.7
15,Goodfellas,1990,8.7
17,One Flew Over the Cuckoo's Nest,1975,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
28,The Silence of the Lambs,1991,8.6
19,Gisaengchung,2019,8.6

In [20]:
# Select all movies directed by Quentin Tarantino.
# Show their title, released year, IMDB rating, and gross.
imdb[imdb['Director'] == 'Quentin Tarantino'][['Series_Title','IMDB_Rating','Released_Year']]

                         Series_Title  IMDB_Rating Released_Year
6                        Pulp Fiction          8.9          1994
62                   Django Unchained          8.4          2012
93               Inglourious Basterds          8.3          2009
103                    Reservoir Dogs          8.3          1992
241                 Kill Bill: Vol. 1          8.1          2003
369                 Kill Bill: Vol. 2          8.0          2004
584                 The Hateful Eight          7.8          2015
879  Once Upon a Time... in Hollywood          7.6          2019

In [24]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
imdb[imdb['Certificate'] == 'R'][['Series_Title','Certificate','IMDB_Rating']].query('IMDB_Rating>=8.5')

           Series_Title Certificate  IMDB_Rating
24  Saving Private Ryan           R          8.6
38          The Pianist           R          8.5
40   American History X           R          8.5

In [26]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
imdb[['Released_Year']].nunique()
#100!

Released_Year    100
dtype: int64

In [27]:
# Count the number of movies in each "Released_Year"?
# Hint: value_counts()
imdb[['Released_Year']].value_counts()

Released_Year
2014             32
2004             31
2009             29
2016             28
2013             28
                 ..
1936              1
1930              1
1921              1
1922              1
PG                1
Name: count, Length: 100, dtype: int64

In [28]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's is not.
# Find this movie.
imdb.groupby('Released_Year').agg({'Released_Year':['min','max']}) #by running this I discovered the "Released_Year" for a movie has the value "PG"

#see below for the next part of the solution

              Released_Year
                        min   max
Released_Year
1920                   1920  1920
1921                   1921  1921
1922                   1922  1922
1924                   1924  1924
1925                   1925  1925
...                     ...   ...
2017                   2017  2017
2018                   2018  2018
2019                   2019  2019
2020                   2020  2020
PG                       PG    PG

[100 rows x 2 columns]

In [33]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_name, column_name] = new_value
imdb.loc[966, 'Released_Year'] = 1995
imdb['Released_Year'].nunique()

100

In [36]:
# Change the data type of "Released_Year" to int
imdb['Released_Year'] = imdb['Released_Year'].astype(int)
imdb['Released_Year'].dtype

dtype('int64')

In [39]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.


imdb[(imdb.Released_Year >= 2010) & (imdb.IMDB_Rating >= 8.5)][['Series_Title','Certificate','IMDB_Rating']]

        Series_Title Certificate  IMDB_Rating
8          Inception          UA          8.8
18          Hamilton       PG-13          8.6
19      Gisaengchung           A          8.6
20   Soorarai Pottru           U          8.6
21      Interstellar          UA          8.6
33             Joker           A          8.5
34          Whiplash           A          8.5
35  The Intouchables          UA          8.5

In [40]:
# Select all movies whose genres contain 'Animation'
imdb[imdb['Genre'].str.contains('Animation')]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
23,https://m.media-amazon.com/images/M/MV5BMjlmZm...,Sen to Chihiro no kamikakushi,2001,U,125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,"10,055,859"
43,https://m.media-amazon.com/images/M/MV5BYTYxNG...,The Lion King,1994,U,88 min,"Animation, Adventure, Drama",8.5,Lion prince Simba and his father are targeted ...,88.0,Roger Allers,Rob Minkoff,Matthew Broderick,Jeremy Irons,James Earl Jones,942045,"422,783,777"
46,https://m.media-amazon.com/images/M/MV5BZmY2Nj...,Hotaru no haka,1988,U,89 min,"Animation, Drama, War",8.5,A young boy and his little sister struggle to ...,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
56,https://m.media-amazon.com/images/M/MV5BODRmZD...,Kimi no na wa.,2016,U,106 min,"Animation, Drama, Fantasy",8.4,Two strangers find themselves linked in a biza...,79.0,Makoto Shinkai,Ryûnosuke Kamiki,Mone Kamishiraishi,Ryô Narita,Aoi Yûki,194838,"5,017,246"
58,https://m.media-amazon.com/images/M/MV5BMjMwND...,Spider-Man: Into the Spider-Verse,2018,U,117 min,"Animation, Action, Adventure",8.4,Teen Miles Morales becomes the Spider-Man of h...,87.0,Bob Persichetti,Peter Ramsey,Rodney Rothman,Shameik Moore,Jake Johnson,375110,"190,241,310"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,https://m.media-amazon.com/images/M/MV5BODkxNG...,Mulan,1998,U,88 min,"Animation, Adventure, Family",7.6,"To save her father from death in the army, a y...",71.0,Tony Bancroft,Barry Cook,Ming-Na Wen,Eddie Murphy,BD Wong,256906,"120,620,254"
971,https://m.media-amazon.com/images/M/MV5BMTY5Nj...,Omohide poro poro,1991,U,118 min,"Animation, Drama, Romance",7.6,A twenty-seven-year-old office worker travels ...,90.0,Isao Takahata,Miki Imai,Toshirô Yanagiba,Yoko Honna,Mayumi Izuka,27071,"453,243"
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,"111,543,479"
986,https://m.media-amazon.com/images/M/MV5BMzZiOD...,Watership Down,1978,U,91 min,"Animation, Adventure, Drama",7.6,Hoping to escape destruction by human develope...,64.0,Martin Rosen,John Hubley,John Hurt,Richard Briers,Ralph Richardson,33656,NaN
992,https://m.media-amazon.com/images/M/MV5BMjAwMT...,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,Bagheera the Panther and Baloo the Bear have a...,65.0,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,"141,843,612"

In [42]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]
stars

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,1956,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,1953,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,1944,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,1935,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [45]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']]
genres

                 Series_Title  Released_Year                     Genre
0    The Shawshank Redemption           1994                     Drama
1               The Godfather           1972              Crime, Drama
2             The Dark Knight           2008      Action, Crime, Drama
3      The Godfather: Part II           1974              Crime, Drama
4                12 Angry Men           1957              Crime, Drama
..                        ...            ...                       ...
995    Breakfast at Tiffany's           1961    Comedy, Drama, Romance
996                     Giant           1956            Drama, Western
997     From Here to Eternity           1953       Drama, Romance, War
998                  Lifeboat           1944                Drama, War
999              The 39 Steps           1935  Crime, Mystery, Thriller

[1000 rows x 3 columns]

In [47]:
# Sorting:
# Sort dataframe genres in ascending order of "Released_Year"
genres.sort_values(by='Released_Year', ascending=True)

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
612    The Trial of the Chicago 7           2020      Drama, History, Thriller
613                          Druk           2020                 Comedy, Drama
20                Soorarai Pottru           2020                         Drama
18                       Hamilton           2020     Biography, Drama, History
205                          Soul           2020  Animation, Adventure, Comedy

[1000 rows x 3 columns]

In [53]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)][['Series_Title','Released_Year','Certificate','Gross']].sort_values(by='Gross', ascending=False)

        Series_Title  Released_Year Certificate        Gross
19      Gisaengchung           2019           A   53,367,844
33             Joker           2019           A  335,451,311
8          Inception           2010          UA  292,576,195
21      Interstellar           2014          UA  188,020,017
35  The Intouchables           2011          UA   13,182,281
34          Whiplash           2014           A   13,092,000
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Does the sorting result look right to you? What's the problem?

#No, it's not in order and 2 rows have a null gross value. It's stored as a string right now so it's being sorted alphabetically and not numerically

In [59]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe

#remove commas
imdb['Gross'] = imdb['Gross'].str.replace(',', '')
#convert to float
imdb['Gross'] = imdb['Gross'].astype(float)
imdb['Gross'].dtype

dtype('float64')

In [60]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)][['Series_Title','Released_Year','Certificate','Gross']].sort_values(by='Gross', ascending=False)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [65]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe

imdb['Runtime_min'] = imdb['Runtime'].str.replace('min','')
imdb['Runtime_min'] = imdb['Runtime_min'].astype(int)
imdb['Runtime_min'].dtype

dtype('int64')

In [71]:
# Add a new column "Age_Year" by expression: Current year - Released_Year

#Asked Gemini how to get the current year so I could set up the calculated column that does the math
import datetime
imdb['Current_Year'] = datetime.datetime.now().year
imdb['Age_Year'] = (imdb['Current_Year'] - imdb['Released_Year'])
imdb['Age_Year']

0      32
1      54
2      18
3      52
4      69
       ..
995    65
996    70
997    73
998    82
999    91
Name: Age_Year, Length: 1000, dtype: int64

In [72]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.

#we did something similar with the 'flights' data
# //10 removes the last digit
# * 10 makes them all end with 0 again
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10
imdb['Decade']

0      1990
1      1970
2      2000
3      1970
4      1950
       ...
995    1960
996    1950
997    1950
998    1940
999    1930
Name: Decade, Length: 1000, dtype: int64

## Part 2: Data Summarization

In [73]:
# Total "Gross" of all top 1000 movies
imdb['Gross'].sum()

np.float64(56536877976.0)

In [75]:
# Average "No_of_Votes" of all movies
imdb['No_of_Votes'].mean()

np.float64(273692.911)

In [78]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
imdb['Decade'].value_counts().sort_values(ascending=False)

Decade
2010    242
2000    237
1990    151
1980     89
1970     76
1960     73
1950     56
1940     35
1930     24
1920     11
2020      6
Name: count, dtype: int64

In [79]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
imdb['Director'].value_counts().sort_values(ascending=False).head(10)

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Martin Scorsese      10
Akira Kurosawa       10
Billy Wilder          9
Stanley Kubrick       9
Woody Allen           9
Quentin Tarantino     8
David Fincher         8
Name: count, dtype: int64

In [82]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Ranked in descending order of total gross
# Show the top 10 directors with the most gross
(
    imdb.groupby('Director')  #groupby director name
    .agg({'Series_Title':'count',
          'IMDB_Rating':'mean',
          'Gross':'sum'})  #perform aggregation on each column seperately
    .sort_values(by= 'Gross', ascending=False).head(10)  #sort desc by gross
    )

                   Series_Title  IMDB_Rating         Gross
Director
Steven Spielberg             13     8.030769  2.478133e+09
Anthony Russo                 4     8.075000  2.205039e+09
Christopher Nolan             8     8.462500  1.937454e+09
James Cameron                 5     8.080000  1.748237e+09
Peter Jackson                 5     8.400000  1.597312e+09
J.J. Abrams                   3     7.833333  1.423171e+09
Brad Bird                     4     7.900000  1.099628e+09
Robert Zemeckis               5     8.120000  1.049446e+09
David Yates                   3     7.800000  9.789537e+08
Pete Docter                   4     8.125000  9.393821e+08

In [87]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count

imdb.groupby(['Decade', 'Director']).agg({'Series_Title':'count','IMDB_Rating':'mean'}).sort_values(by='Series_Title',ascending=False)

                             Series_Title  IMDB_Rating
Decade Director
1950   Billy Wilder                     6     8.133333
       Akira Kurosawa                   5     8.260000
2010   Denis Villeneuve                 5     7.980000
1950   Alfred Hitchcock                 5     8.220000
1980   Steven Spielberg                 5     7.980000
...                                   ...          ...
2010   Tyler Nilson                     1     7.600000
       Umesh Shukla                     1     8.100000
       Vikas Bahl                       1     8.200000
       Vikramaditya Motwane             1     8.200000
       Vishal Bhardwaj                  1     8.100000

[749 rows x 2 columns]

In [90]:
# Find the top 3 highest rated movies of each year since 2010. - 'Ranking' column
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking

# must calculate a 'Ranking' column for each movie within its decade, based on IMDB_Rating -
                  #I asked Gemini how to get the top 3 by decade since I couldn't find in my notes how to return that and store it as a new column
imdb['Ranking'] = imdb.groupby('Released_Year')['IMDB_Rating'].rank(method='first', ascending=False) # it's grouping by Released_Year and then pulling IMDB_Ranking to do the .rank

# Now, filter for movies that are in the top 3 of their decade and are from decades since 2010
# Then select the desired columns and sort them as requested
( imdb[
    (imdb['Ranking'] <= 3) & (imdb['Released_Year'] >= 2010)
][
    ['Released_Year', 'Ranking', 'Series_Title', 'IMDB_Rating']
].sort_values(by=['Released_Year', 'Ranking'], ascending=[False, True])
)

     Released_Year  Ranking                       Series_Title  IMDB_Rating
18            2020      1.0                           Hamilton          8.6
20            2020      2.0                    Soorarai Pottru          8.6
205           2020      3.0                               Soul          8.1
19            2019      1.0                       Gisaengchung          8.6
33            2019      2.0                              Joker          8.5
59            2019      3.0                  Avengers: Endgame          8.4
53            2018      1.0                         Capharnaüm          8.4
58            2018      2.0  Spider-Man: Into the Spider-Verse          8.4
60            2018      3.0             Avengers: Infinity War          8.4
54            2017      1.0          Ayla: The Daughter of War          8.4
55            2017      2.0                       Vikram Vedha          8.4
61            2017      3.0                               Coco          8.4
56            2016      1.0                     Kimi no na wa.          8.4
57            2016      2.0                             Dangal          8.4
196           2016      3.0                               Pink          8.1
133           2015      1.0                             Talvar          8.2
136           2015      2.0                           Drishyam          8.2
203           2015      3.0                               Room          8.1
21            2014      1.0                       Interstellar          8.6
34            2014      2.0                           Whiplash          8.5
200           2014      3.0                              Mommy          8.1
87            2013      1.0                           Drishyam          8.3
137           2013      2.0                              Queen          8.2
138           2013      3.0                        Mandariinid          8.2
62            2012      1.0                   Django Unchained          8.4
63            2012      2.0              The Dark Knight Rises          8.4
88            2012      3.0                             Jagten          8.3
35            2011      1.0                   The Intouchables          8.5
89            2011      2.0            Jodaeiye Nader az Simin          8.3
144           2011      3.0                            Warrior          8.2
8             2010      1.0                          Inception          8.8
90            2010      2.0                          Incendies          8.3
141           2010      3.0                              Udaan          8.2

In [94]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.

# Group by Director and Decade to get movie count for each combination
decade_movie_count = imdb.groupby(['Director', 'Decade']).size().reset_index(name='Movie_Count')

# Find directors with movies in at least 5 different decades
directors_with_five = decade_movie_count.groupby('Director')['Decade'].nunique()
directors_with_five = directors_with_five[directors_with_five >= 5].index

# Filter the decade_movie_counts to only include these directors
final_result = decade_movie_count[decade_movie_count['Director'].isin(directors_with_five)]

final_result.sort_values(by=['Director', 'Decade'])

             Director  Decade  Movie_Count
247    Hayao Miyazaki    1970            1
248    Hayao Miyazaki    1980            4
249    Hayao Miyazaki    1990            2
250    Hayao Miyazaki    2000            3
251    Hayao Miyazaki    2010            1
424   Martin Scorsese    1970            1
425   Martin Scorsese    1980            3
426   Martin Scorsese    1990            2
427   Martin Scorsese    2000            1
428   Martin Scorsese    2010            3
644  Steven Spielberg    1970            2
645  Steven Spielberg    1980            5
646  Steven Spielberg    1990            3
647  Steven Spielberg    2000            2
648  Steven Spielberg    2010            1

In [95]:
# Ask two questions about this dataset and write your code to answer them.
# Question 1: what are the top 10 highest grossing genres
imdb.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(10)
#this would be better answered if we split the genres column up so each genre column only had one value for genre

Genre
Action, Adventure, Sci-Fi       5.898659e+09
Animation, Adventure, Comedy    4.503338e+09
Action, Adventure, Drama        2.668836e+09
Action, Adventure, Fantasy      2.116341e+09
Drama                           2.020898e+09
Animation, Action, Adventure    2.008695e+09
Drama, Romance                  1.962892e+09
Action, Adventure, Comedy       1.920414e+09
Action, Crime, Drama            1.309042e+09
Biography, Drama, History       1.272648e+09
Name: Gross, dtype: float64

In [96]:
# Questions 2: what 10 directors have the highest avg IMBD rating
imdb.groupby('Director')['IMDB_Rating'].mean().sort_values(ascending=False).head(10)

Director
Frank Darabont        8.95
Lana Wachowski        8.70
Irvin Kershner        8.70
Masaki Kobayashi      8.60
Fernando Meirelles    8.60
George Lucas          8.60
Sudha Kongara         8.60
Thomas Kail           8.60
Roberto Benigni       8.60
Milos Forman          8.50
Name: IMDB_Rating, dtype: float64